services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  backend:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/srv/shortlink
      - ./shared:/shared
    command: gunicorn api.main:app -w 1 -k uvicorn.workers.UvicornWorker -b :8080 -t 180
    env_file:
      - .env
    tty: true
    restart: always
    depends_on:
      - db
